Added db scanning capability
AppsFlyer/aerospike-clj pull request #23
Opened 2020-02-03 13:56 UTC by yaronel

Added a new feature that is available in the Aerospike java client - the ability to retrieve or perform operations on all the records in a set.
Some use cases: 
- Iterating over the records in a set and pushing them to a queue for processing, or to another data store.
- Collecting all the records and returning them.
- Programmatically and selectively performing different operations on records.

The implementation exposes the functionality of `public final void scanAll(EventLoop eventLoop, RecordSequenceListener listener, ScanPolicy policy, String namespace, String setName, String... binNames) throws AerospikeException` from `com.aerospike.client`.
  
The function is documented, and the tests show what you can and cannot do.

On a side note, I know it says not to mix other changes with the PR. But a few slipped in:
- Added some common files to .gitignore
- Added type hints where the compiler was complaining.
- Fixed one typo

2020-02-20 11:17 UTC, barkanido requested changes
LGTM. I would change the stop scan sentinel to a keyword which is a bit more expected. other than that: good job!

2020-02-20 11:17 UTC, barkanido commented on src/aerospike_clj/client.clj
> +  ABORT-SCAN "ABORT-SCAN")
replace with `:ABORT-SCAN`?

2020-02-20 17:41 UTC, yaronel commented on src/aerospike_clj/client.clj
> +  ABORT-SCAN "ABORT-SCAN")
Right, makes sense. I’ll update.

2020-02-27 07:15 UTC, yaronel commented on src/aerospike_clj/client.clj
> +  ABORT-SCAN "ABORT-SCAN")
Updated: https://github.com/AppsFlyer/aerospike-clj/pull/23/files/93b835ce2fd9da43ed32192880a99f1902937e54..af21e3e54a1fe2cd11d060193ca83431eb54e05c

2020-02-27 12:27 UTC, barkanido approved these changes
LGTM!

2020-03-01 10:37 UTC, merged