Remove unused setter calls in map->event-policy
AppsFlyer/aerospike-clj pull request #45
Opened 2020-09-04 15:44 UTC by predar

2020-09-06 14:54 UTC, barkanido requested changes
Thanks a lot!

and kudos for the test addition.
overall, LGTM.

2020-09-06 14:54 UTC, barkanido commented on test/aerospike_clj/policy_test.clj
> +  (is (= (get conf "maxCommandsInProcess" 0) (.-maxCommandsInProcess event-policy)))
I do not think there is a need for the `.-` accessor:
```clojure
=> (import '[com.aerospike.client.async EventPolicy])
=> (def ep (EventPolicy.))
=> (.minTimeout ep)
100
```

2020-09-07 10:24 UTC, barkanido approved these changes

2020-09-07 10:25 UTC, barkanido commented
Thanks! merging.

2020-09-07 10:25 UTC, merged

2020-09-07 10:49 UTC, predar commented
> Thanks! merging.

Great. Glad I could help. Thank you, too!