Optimize record->map
AppsFlyer/aerospike-clj pull request #61
Opened 2022-11-29 13:22 UTC by evg-tso

In this PR:

1. Avoid costly `(into {} ..)`, we can use the original `(.bins record)`.
2. No need for the `keys` function, since we can rely on the previously extracted `(.bind record)`.
3. `sanitize-bin-value` and `desanitize-bin-value` don't need to cast a single item to a vector, apply a transducer and extract the first item from the result, this can be unrolled into a single `(get ...)` function.
4. Use `Map`'s methods to determine if it is a single bin, and avoid costly vector comparison.

See the attached CPU sampling flame graph to see the tackled hot spots.  
![image](https://user-images.githubusercontent.com/1637415/204539697-81e28eca-af30-4374-b41f-7307fa415a1c.png)

2022-11-29 14:44 UTC, asafch requested changes
You also need to bump the version in `project.clj` and update `CHANGELOG.md`.

2022-11-29 17:36 UTC, evg-tso commented
@asafch, done.

2022-11-29 18:34 UTC, evg-tso commented
I've profiled the proposed PR in an internal service, under the same load as in the PR's description.  
I can see that the `aerospike-record/record->map` shows up less in the CPU samples and a shallower stacktrace.  

Before:
![image](https://user-images.githubusercontent.com/1637415/204616204-4a3668b3-d087-435a-add0-5688f5196f73.png)

After:  
![image](https://user-images.githubusercontent.com/1637415/204616295-11a66e4c-d7b4-4c40-95f2-db7f3569e86e.png)

2022-11-30 07:28 UTC, asafch approved these changes

2022-12-01 15:04 UTC, merged